services:
  - type: web
    name: love-match
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: API_KEY
        value: love-match-2024
